version: '3.8'

services:
  motel_reports_web:
    build: .
    restart: always
    ports:
      - "8080:80" # Acessar via http://localhost:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
